projectInfo = [
  {
    name: "Factory Generator with Multi-User Support",
    value: "node_factory",
    stack: ["MERN - Mongo DB, Express, React, Node"],
    other: ["Pusher IO"],
    description: []
  },
  {
    name: "Interactive Game Resource Map",
    value: "resource_map",
    stack: ["REN -React, Express, Node"],
    other: ["Corel Image Editing Suite"],
    description: ["I built this tool when I started playing Fallout 76, an " +
    "open-world RPG set in a post-nuclear-war Applachia, specifically West Virginia. " +
    ""]
  },
  {
    name: "Geovane (beta)",
    value: "geovane",
    stack: ["MEHN - Mongo DB, Express, Handlebars, Node"],
    other: ["Google Maps API, Open Weather API, Corel Image Editing Suite"],
    description: ["This project stemmed from the first group project I "+
    "worked on in UNCC's coding bootcamp. One of my group partners and I " + 
    "had relocated to the Charlotte area from up north and would often " + 
    "drive long distances. One thing we both noted was that it was " + 
    "difficult to find concise weather forecasts for an extended trip. " +
    "We decided to build a tool that could solve that issue",
    "Using Google Maps to plot a route, we could pull geolocation data " +
    "from the information returned by the Google Maps API to run a " + 
    "query to the Open Weather API to get the current weather at that location. "+ 
    "We could then overlay a weather icon along the route generated by Google Maps. " + 
    "I also created several custom avatars to show what the current weather was in a " + 
    "UI designed for those with either a) reading diffulties or b) a preference " + 
    "for a visual representation of data versus a textual representation.",
    "This beta version is built on a full stack, whereas the alpha version "+
    " - created in bootcamp - was built on a static frontend website, with no potential "+
    "to create user profiles and favorites. This beta version lays the "+
    "framework to include that functionality, as well as query weather forecasts, "+
    "not just the current weather."]
  },
  {
    name: "Retail Site Recreation",
    value: "retail_page",
    stack: ["HEN - Handlebars, Express, Node"],
    other: ["Custom Dataset"],
    description: ['Made as a coding challenge.']
  },
  {
    name: "Test",
    value: "test",
    stack: ["MERN: Mongo DB, Express, React, Node"],
    other: ["Pusher IO"],
    description: ['This','is','a','test']
  }
]

module.exports = projectInfo;